services:
  chatgpt:
    build:
      context: .
      target: builder
    env_file: .env
    # if you use a reverse proxy, may not need to expose port
    # ports:
    #   - '8081:8081'
    volumes:
      - .:/app